### ISSUE TITLE
checkAMatHome >> homeLocation.latitude and/or homeLocation.longitude not set or failure on reading!

### ISSUE THREAD

**Issue by tukey42** [truegreyhound/ioBroker.husq-automower#10]
I have a 430X connected to iobroker. It seems to work except that I got the above mentioned message whenever the adpater polls Husqvarna. It seems that the adapter is getting 0 for latitude and longitude from Husqvarna.

**Comment by stsch83** [comment]
i have the same setup with the same error. If i try to set the right values in the objects, they will be overwrite again.

**Comment by truegreyhound** [comment]
Please update to the new version is comming.

**Comment by tukey42** [comment]
Sorry, that I did not answer earlier. I have version 1.1.0 installed, but the error still exists.
