### ISSUE TITLE
Verwendung von 2 automowern - automower wird nicht automtisch aktualisiert

### ISSUE THREAD

**Issue by betonix70** [truegreyhound/ioBroker.husq-automower#11]
Hallo,

erstmal ein großes Danke für den Adapter!

Ich habe ein Frage. Ich habe jetzt den Adapter ein 2. Mal installiert und die Daten des 2. automowers hinterlegt. So weit funktioniert alles. Beide Mäher sind steuerbar. Allerdings wird der 2. automower (der als letzter installiert wurde) nicht mehr automatisch aktualisiert. Startet man den Adapter neu oder ändert man an den Einstellungen etwas und speichert diese werden die Daten aktualisiert.

Kan mir hier jemand helfen?

folgende Logs habe ich zum automower gefunden:

husq-automower.1 | 2020-07-29 13:42:20.575 | warn | (50886) updateStatus, result.operatingMode === HOME
husq-automower.1 | 2020-07-29 13:42:20.331 | info | (50886) connected, mowersListUpdated, found 2 mower(s)
husq-automower.1 | 2020-07-29 13:42:20.090 | info | (50886) Logged on. Checking for mowers.
husq-automower.1 | 2020-07-29 13:42:19.600 | info | (50886) Logged off.
husq-automower.1 | 2020-07-29 13:42:19.556 | info | (50886) starting. Version 1.0.2 in /opt/iobroker/node_modules/iobroker.husq-automower, node: v10.22.0, js-controller: 3.1.6

husq-automower.0 | 2020-07-29 13:41:02.958 | info | (50680) Terminated (NO_ERROR): Without reason
husq-automower.0 | 2020-07-29 13:41:02.956 | info | (50680) terminating
husq-automower.0 | 2020-07-29 13:41:02.949 | info | (50680) cleaned everything up...
husq-automower.0 | 2020-07-29 13:41:02.948 | info | (50680) Logged off.
husq-automower.0 | 2020-07-29 13:41:02.947 | error | at Timer.processTimers (timers.js:223:10)
husq-automower.0 | 2020-07-29 13:41:02.947 | error | at listOnTimeout (timers.js:263:5)
husq-automower.0 | 2020-07-29 13:41:02.947 | error | at tryOnTimeout (timers.js:300:5)
husq-automower.0 | 2020-07-29 13:41:02.947 | error | at ontimeout (timers.js:436:11)
husq-automower.0 | 2020-07-29 13:41:02.947 | error | at Timeout.updateStatus [as _onTimeout] (/opt/iobroker/node_modules/iobroker.husq-automower/main.js:991:15)
husq-automower.0 | 2020-07-29 13:41:02.947 | error | (50680) TypeError: mobjMower.getStatus is not a function
husq-automower.0 | 2020-07-29 13:41:02.946 | error | (50680) uncaught exception: mobjMower.getStatus is not a function
husq-automower.0 | 2020-07-29 13:41:01.943 | info | (50680) Logged off.
husq-automower.0 | 2020-07-29 13:41:01.864 | info | (50680) starting. Version 1.0.2 in /opt/iobroker/node_modules/iobroker.husq-automower, node: v10.22.0, js-controller: 3.1.6

Vielen Dank

**Comment by truegreyhound** [comment]
Bei mir hat das immer funktioniert. Ggf. mit einem 2. Konto arbeiten.
