### ISSUE TITLE
fehlende Daten

### ISSUE THREAD

**Issue by hartwigm** [truegreyhound/ioBroker.husq-automower#12]
ich habe den neuen 435x awd und vermisse die folgenden Funktionen.

Einstellen der Schnitthöhe von 1..9. Usecase: Jahreszeitabhängig bzw. Feuchtigkeitsabhängig umstellen
Einschalten der Scheinwerfer: Usecase: Der Robbi soll ohne Licht auch Nachts fahren, wenn aber eine Bewegung immGarten detektiert wird soll er mit Licht fahren

Wäre super, wenn diese beiden schaltkommandos noch Eingang finden würden.

**Comment by truegreyhound** [comment]
Hi, hätte ich auch gern, ist sogar teilweise Code dafür da, aber die API gibt das offiziell nicht her.
